name: Trivy Security Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t linux-base .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: image
          image-ref: linux-base
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH,MEDIUM
